### ISSUE TITLE
Move external link to metadata page into module settings page

### ISSUE THREAD

**Issue by nadavkav** [PoetOS/moodle-local_metadata#1]
Recently, I found out that as of Moodle 3.1 we can hook into the module's settings form page and add extra form elements by extending plugin_extend_coursemodule_standard_elements() and implementing it inside an plugin. (see https://github.com/moodle/moodle/blob/master/course/moodleform_mod.php#L708)

How about moving the metadata form fields which are now on a separate page into the module's settings page, under a new section (header) ?

**Comment by mchurchward** [comment]
That would probably work. I just need to figure out how that actually works.

**Comment by nadavkav** [comment]
We are on it, and will send a PR soon. (also for the #3 )

**Comment by nadavkav** [comment]
Also, maybe push it into the course front page "edit" menu we have for each module. (so you do not have to go into the module to look for the metadata menu). we are still exploring this with our teachers.

**Comment by mchurchward** [comment]
Steps you'll need to do:

1. Add `local_metadata_coursemodule_standard_elements` to `lib.php`. Have it do something similar to the functions above (e.g. `local_metadata_extend_navigation_user_settings`).
2. Add `public function coursemodule_standard_elements($formwrapper, $mform)` to `classes/context/context_handler.php` similar to the functions before it (e.g. `extend_navigation_user_settings`).
3. Implement the `coursemodule_standard_elements` function in the module context subplugin (`context/module/classes/context_handler.php`).

**Comment by nadavkav** [comment]
Thank you! I will.

**Comment by mchurchward** [comment]
Hi @nadavkav . Are you working on this one?

**Comment by nadavkav** [comment]
I planned to, but did not get around to it.
If it is low priority (nobody but us need asked for it), I would love to be assigned for this. 
As I feel I will have time for this in the next few weeks.

**Comment by mchurchward** [comment]
No worries. I'll leave it unassigned for now.

**Comment by seb-vial** [comment]
Hello,

I was trying to implement this feature which would be needed for us as well.
I followed your instruction @mchurchward but I'm having a hard time implementing the `coursemodule_standard_elements` function in `context/module/classes/context_handler.php`. I just can't figure out how to use the existing form (`context/module/classes/output/manage_date_form.php`) inside this function.
And that led me to an important question, would it create a form inside the original form, if that's the case, we would have to save the module (the global `Save` button at the end of the page) and then we would have to save the metadata form inside the new section we added to the existing module form ?

**Comment by mchurchward** [comment]
That form is currently used in "index.php" on line 141. Perhaps that use can provide you the hints you need?

**Comment by seb-vial** [comment]
Thanks, now I know how to invoke the form and instantiate it but the question is how to include it in the settings form of the module.
`coursemodule_standard_elements($formwrapper, $mform)` gives you a form, I'm far from being an expert in moodle dev, not enough documentation on the matter...

But even though I succeed and the metadata form is located in a new section of the module settings form, we would have a form inside a form, which means there are two different actions. On module creation, we can't send the metadata form, the module doesn't exist yet (there might be a way to insert the metadata form only if the module has already been created ? But not ideal IMO). On edition we would have to save the metadata form individually, which is not the best option UX wise I think...

**Comment by mchurchward** [comment]
You can see a plugin using coursemodule_standard_elements at https://github.com/mchurchward/moodle/blob/MOODLE_33_STABLE/admin/tool/lp/lib.php#L133
You don't add forms to forms. You use the form that is passed in and add form elements to it.
I think that's what you need.

**Comment by seb-vial** [comment]
I think I've finally managed to do it, I was a bit busy this last few weeks and couldn't get to it.
The code probably needs some improvement though, I'll make a PR so you can check it out and tell me what you think about it.

I wanted to use some of your functions, unfortunately that was a bit to specific to the plugin behavior, I had to copy/paste some of it in the hooks.

PR => #8
