### ISSUE TITLE
Is there an API for extracting the metatda?

### ISSUE THREAD

**Issue by leac** [PoetOS/moodle-local_metadata#2]
I created a few metadada fields for *courses*, and now would like to display them in a block I'm creating.  
To start with I extracted them by using DB queries, but I'm wondering if there is a more abstracted way to do it. Are there functions for getting all fields and all values?

When I need an array of all fields in courses, I use:
`       $allcoursefields = $DB->get_records('local_metadata_field', array('contextlevel' => CONTEXT_COURSE));`

And when I want to get all the values of a certain course, I use:
` $select = "instanceid = " . $courseid . " AND fieldid in (" . implode(',', $allcoursefieldsids) . ")";`
` $allcoursefieldsvalues = $DB->get_records_select('local_metadata', $select);`

Is there a better way to do this?

**Comment by mchurchward** [comment]
I haven't created an API, although it would be great to have one, especially through external services.
The best way is with SQL something like:

```
$sql = "SELECT lm.id, lm.data
FROM {local_metadata} lm
INNER JOIN {local_metadata_field} lmf ON lm.fieldid = lmf.id
WHERE lmf.contextlevel = ? AND lm.instanceid = ?";
$params = [CONTEXT_COURSE, $courseid];
$records = $DB->get_records_sql($sql, $params);
```

Hope this helps.

**Comment by mchurchward** [comment]
If you want to do multiple courseids, and you have them in an array, you would want something like this:
```
list($cnd, $params) = $DB->get_in_or_equal($courseids);
$sql = "SELECT lm.id, lm.data
FROM {local_metadata} lm
INNER JOIN {local_metadata_field} lmf ON lm.fieldid = lmf.id
WHERE lmf.contextlevel = ? AND lm.instanceid " . $cnd;
$params = array_merge([CONTEXT_COURSE], $params);
$records = $DB->get_records_sql($sql, $params);
```

**Comment by Ludoutt** [comment]
Hello
We've just started a "massimporter" metadata for courses using CSV files so we created some getters for our projet but... if an API could be including in metadata projet  it cool be cool ;)

https://github.com/moodlemoot/moodle-local_massinsertmetadata

**Comment by mchurchward** [comment]
I think an API would be great. Any chance you could start providing some ideas of what types of API calls you would like? That would help me sketch out a plan for implementing the API.

**Comment by Ludoutt** [comment]
Hello,

 if you can provide getter and setter and persistance method for localmetadata objet, it could be nice (we wrote some method to do the job instead..)

If you can provide somme REST (with json format) API entries  for managing localmetadata and their definition (GET, POST, PUT, DELETE) throw webservices it coul be usefull to use your plugin with any ETL to synchronize our information system with moodle localmetadata (synchronize course catalog for example)

How can I help you to sketch out a plan for implementing the API ?

**Comment by mchurchward** [comment]
I think we need to list out what functions we would want first. Unless you have other ideas. What would be good would be to list out the user stories defining how the API would be used, as well as some specific function statements.
Something like:
"Get all metadata instances for the user with id 'X'".
"Get all metadata instances matching the name 'X' for any context".
and so on....

But if you have other ideas, start with the top-level statement of what you think we should do. I'll be happy to set up a collaborative document we can use once we have a basic start.

**Comment by nadavkav** [comment]
I am also interested in a collaberative document, as we are retriving the data directly from the DB tables at the moment.

**Comment by mchurchward** [comment]
Hi Nadav. Can you list out what the data is that you are currently getting direct? That will help determine what we want to create API's for.

**Comment by nadavkav** [comment]
I have it installed and used in two different Moodle projects.
In one, we have just a few metadata fields on a category context level and a course context level.
and on the other, which is using your older version of the plugin (before the refactor), we use 12+ different fields (and also developed new fileupload and multimenu field types)
https://github.com/PeTeL-Weizmann/moodle/tree/petel_prod/local/metadata/classes/metadata/fileupload
https://github.com/PeTeL-Weizmann/moodle/tree/petel_prod/local/metadata/classes/metadata/multimenu
(We have started refactoring them into your new version, current master branch)

We are reading the metadata directly from the DB tables as part of a complex SQL query:
https://github.com/PeTeL-Weizmann/moodle/blob/petel_prod/local/oercatalog/classes/classFilterPage.php#L462

But I prefer we used proper API (a class) for it.
Maybe...
$metadata = new Metadata();
$metadata_course = $metadata->get_metadata(CONTEXT_COURSE, $courseid);
foreach ($metadata_course as $key => $fields) {
    print_object($field->data);
}
What do you think?

**Comment by nadavkav** [comment]
Or maybe:
$metadata->get_full_metadata(CONTEXT_COURSE, $courseid);
$metadata->get_field_metadata(CONTEXT_USER, $courseid, array('age' => '12', 'gender' => 'male'));

**Comment by nadavkav** [comment]
@kirildevlion What do you think?

**Comment by mchurchward** [comment]
Closing due to passage of time with no action. Please create a new issue for creating an external API if there is interest.
