### ISSUE TITLE
Adding new field type in branch MOODLE_32_SUBPLUGINS

### ISSUE THREAD

**Issue by leac** [PoetOS/moodle-local_metadata#3]
I want to add a file upload field type. Now, in branch master, all I had to do was add a folder named `fileupload` to `classes/metadata` folder.  
But in the MOODLE_32_SUBPLUGINS branch, things changed and there's no longer a `metadata` folder under `classes`. So how do I add the new file type here?

**Comment by mchurchward** [comment]
Hi.
The plugin now supports two subplugin types: fieldtypes and contexts.
Fieldtypes is what the original one was. They are stored in the `fieldtype` subdirectory structure.
Contexts define the type of Moodle objects that can have fieldtypes assigned to them and are in the `context` subdirectory.
You can see the subplugins definition in the `db/subplugins.php` file.
Hope this helps. I look forward to your contribution.
