### ISSUE TITLE
[question] API to retrieve custom metadata?

### ISSUE THREAD

**Issue by tmuras** [PoetOS/moodle-local_metadata#7]
Is there an API to retrieve the values for the custom metadata if I'd like to use it from my plugin? For example to get a value for custom course metadata?

**Comment by mchurchward** [comment]
Hi. Can you read [Issue 2](https://github.com/PoetOS/moodle-local_metadata/issues/2), and provide some feedback there? This request is already being dicussed there.
I'm going to close this one.
