### ISSUE TITLE
metadata to work with moodle 2.9 version

### ISSUE THREAD

**Issue by sudeeptldy** [PoetOS/moodle-local_metadata#9]
When I try to change the version.php to work with moodle 2.9 version, I am not able to get all the contexts in the metadata module.

**Comment by sudeeptldy** [comment]
Hi I am not able to assign anyone on this improvement

**Comment by mchurchward** [comment]
Hi. Who are you trying to assign? I don't think anyone is going to try to make this work with 2.9.
